### ISSUE TITLE
757: unexpected token at '404 page not found'

### ISSUE THREAD

**Issue by ramakuka** [CenturyLinkLabs/fleet-api#10]
Hey , 
I just upgraded fleet-api to version 1.1.0 from 0.9.0 and I it looks like there are some issues.
I am using clinet.status to get the status of the unit and also to know if unit already exist 
here is my status method 
```
  def status
    @ustatus ||= @ustatus = "none"
    begin
     @ustatus=fleet.status(unitname)
    rescue Fleet::NotFound
      nil
    end
  end
```
When trying to use 1.1.0 I keep getting Json parser error - quick look at the code shows that you are trying to parse all errors - but 404 error is not parable (probably not in a json format).
here is the exception :
```
 757: unexpected token at '404 page not found'
/root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
/root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:51:in `raise_error'
/root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:31:in `request'
 /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/request.rb:11:in `block (2 levels) in <module:Request>'
/root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/fleet-api-1.1.0/lib/fleet/client/unit.rb:12:in `get_unit'
```

So the question is why is it not returning Fleet::NotFound like in 0.9.0? and how can we change "404 not found" to be parseable by json parser ?

**Comment by bdehamer** [comment]
@ramakuka One important thing to note about the upgrade from version 0.9.0 of the gem to version 1.1.0 is that the underlying API has fundamentally changed. With version 0.9.0, the gem talked directly to etcd. Version 1.1.0 of the gem was re-written to communicate with the new, official Fleet REST API (which should be more reliable/stable than the old approach where we had essentially reverse-engineered the communication between `fleetctl` and etcd).

When upgrading to 1.1.0 you'll need to make sure that you configure the gem to point to the Fleet API endpoint instead of the etcd endpoint.

I suspect that this may be why you are receiving a 404 error with your status call and why the gem is having difficult parsing the response (with the new Fleet API, all of the error responses return a JSON body).

Please let me know if you continue to have problems.

**Comment by ramakuka** [comment]
Thanks ,
I will check it out , and let you know .

**Comment by ramakuka** [comment]
Ok - I changed the application to use the fleet API , and it seems to work .

Thanks for the quick response .

**Comment by bdehamer** [comment]
Let me know if you need any additional help.
